sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.15.0

install:
  - docker-compose up -d

script:
  - docker-compose exec web24 bash -lc "which bundle" || (printf "\nbundle not found! Test failed."; exit 1)
  - docker-compose exec web24 bash -lc "which gcloud" || (printf "\ngcloud ot found! Test failed."; exit 1)
